Task 7 : Implement Hyperparameter Tuning

 Task: Optimize model hyperparameters.
 Details:
 Use tools like GridSearchCV or RandomizedSearchCV to find the best hyperparameters for a model.
 Evaluate the impact of different hyperparameters on model performance.

In [63]:
import pandas as pd
import numpy as n
from sklearn.preprocessing import OneHotEncoder

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

Data preprocessing and data Uploaded

In [64]:
df = pd.read_csv('winequality.csv')
df

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0     white            7.0             0.270         0.36            20.7   
1     white            6.3             0.300         0.34             1.6   
2     white            8.1             0.280         0.40             6.9   
3     white            7.2             0.230         0.32             8.5   
4     white            7.2             0.230         0.32             8.5   
...     ...            ...               ...          ...             ...   
6492    red            6.2             0.600         0.08             2.0   
6493    red            5.9             0.550         0.10             2.2   
6494    red            6.3             0.510         0.13             2.3   
6495    red            5.9             0.645         0.12             2.0   
6496    red            6.0             0.310         0.47             3.6   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0         0.045                 45.0                 170.0  1.00100  3.00   
1         0.049                 14.0                 132.0  0.99400  3.30   
2         0.050                 30.0                  97.0  0.99510  3.26   
3         0.058                 47.0                 186.0  0.99560  3.19   
4         0.058                 47.0                 186.0  0.99560  3.19   
...         ...                  ...                   ...      ...   ...   
6492      0.090                 32.0                  44.0  0.99490  3.45   
6493      0.062                 39.0                  51.0  0.99512  3.52   
6494      0.076                 29.0                  40.0  0.99574  3.42   
6495      0.075                 32.0                  44.0  0.99547  3.57   
6496      0.067                 18.0                  42.0  0.99549  3.39   

      sulphates  alcohol  quality  
0          0.45      8.8        6  
1          0.49      9.5        6  
2          0.44     10.1        6  
3          0.40      9.9        6  
4          0.40      9.9        6  
...         ...      ...      ...  
6492       0.58     10.5        5  
6493        NaN     11.2        6  
6494       0.75     11.0        6  
6495       0.71     10.2        5  
6496       0.66     11.0        6  

[6497 rows x 13 columns]

In [65]:
df.head()

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0  white            7.0              0.27         0.36            20.7   
1  white            6.3              0.30         0.34             1.6   
2  white            8.1              0.28         0.40             6.9   
3  white            7.2              0.23         0.32             8.5   
4  white            7.2              0.23         0.32             8.5   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.045                 45.0                 170.0   1.0010  3.00   
1      0.049                 14.0                 132.0   0.9940  3.30   
2      0.050                 30.0                  97.0   0.9951  3.26   
3      0.058                 47.0                 186.0   0.9956  3.19   
4      0.058                 47.0                 186.0   0.9956  3.19   

   sulphates  alcohol  quality  
0       0.45      8.8        6  
1       0.49      9.5        6  
2       0.44     10.1        6  
3       0.40      9.9        6  
4       0.40      9.9        6

In [66]:
df.tail()

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
6492  red            6.2             0.600         0.08             2.0   
6493  red            5.9             0.550         0.10             2.2   
6494  red            6.3             0.510         0.13             2.3   
6495  red            5.9             0.645         0.12             2.0   
6496  red            6.0             0.310         0.47             3.6   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
6492      0.090                 32.0                  44.0  0.99490  3.45   
6493      0.062                 39.0                  51.0  0.99512  3.52   
6494      0.076                 29.0                  40.0  0.99574  3.42   
6495      0.075                 32.0                  44.0  0.99547  3.57   
6496      0.067                 18.0                  42.0  0.99549  3.39   

      sulphates  alcohol  quality  
6492       0.58     10.5        5  
6493        NaN     11.2        6  
6494       0.75     11.0        6  
6495       0.71     10.2        5  
6496       0.66     11.0        6

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   type                  6497 non-null   object 
 1   fixed acidity         6487 non-null   float64
 2   volatile acidity      6489 non-null   float64
 3   citric acid           6494 non-null   float64
 4   residual sugar        6495 non-null   float64
 5   chlorides             6495 non-null   float64
 6   free sulfur dioxide   6497 non-null   float64
 7   total sulfur dioxide  6497 non-null   float64
 8   density               6497 non-null   float64
 9   pH                    6488 non-null   float64
 10  sulphates             6493 non-null   float64
 11  alcohol               6497 non-null   float64
 12  quality               6497 non-null   int64  
dtypes: float64(11), int64(1), object(1)
memory usage: 660.0+ KB


In [68]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    6487.000000       6489.000000  6494.000000     6495.000000   
mean        7.216579          0.339691     0.318722        5.444326   
std         1.296750          0.164649     0.145265        4.758125   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.400000          0.230000     0.250000        1.800000   
50%         7.000000          0.290000     0.310000        3.000000   
75%         7.700000          0.400000     0.390000        8.100000   
max        15.900000          1.580000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  6495.000000          6497.000000           6497.000000  6497.000000   
mean      0.056042            30.525319            115.744574     0.994697   
std       0.035036            17.749400             56.521855     0.002999   
min       0.009000             1.000000              6.000000     0.987110   
25%       0.038000            17.000000             77.000000     0.992340   
50%       0.047000            29.000000            118.000000     0.994890   
75%       0.065000            41.000000            156.000000     0.996990   
max       0.611000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality  
count  6488.000000  6493.000000  6497.000000  6497.000000  
mean      3.218395     0.531215    10.491801     5.818378  
std       0.160748     0.148814     1.192712     0.873255  
min       2.720000     0.220000     8.000000     3.000000  
25%       3.110000     0.430000     9.500000     5.000000  
50%       3.210000     0.510000    10.300000     6.000000  
75%       3.320000     0.600000    11.300000     6.000000  
max       4.010000     2.000000    14.900000     9.000000

In [69]:
df.drop_duplicates(inplace= True)

In [70]:
df.isnull().sum()

type                     0
fixed acidity           10
volatile acidity         8
citric acid              3
residual sugar           2
chlorides                2
free sulfur dioxide      0
total sulfur dioxide     0
density                  0
pH                       9
sulphates                4
alcohol                  0
quality                  0
dtype: int64

In [71]:
df.shape

(5329, 13)

Filled the missing values

In [72]:
df['fixed acidity'] = df['fixed acidity'].mean()
df.fillna(df['fixed acidity'], inplace = True)


df['volatile acidity'] = df['volatile acidity'].mean()
df.fillna(df['volatile acidity'], inplace = True)


df['citric acid'] = df['citric acid'].mean()
df.fillna(df['citric acid'], inplace = True)


df['residual sugar'] = df['residual sugar'].mean()
df.fillna(df['residual sugar'], inplace = True)


df['chlorides'] = df['chlorides'].mean()
df.fillna(df['chlorides'], inplace = True)


df['pH'] = df['pH'].mean()
df.fillna(df['pH'], inplace = True)


df['sulphates'] = df['sulphates'].mean()
df.fillna(df['sulphates'], inplace = True)

transform the type col , categorical to numerical by onehot encoder

In [73]:
df['type'].unique()

array(['white', 'red'], dtype=object)

In [74]:
ohe = OneHotEncoder(sparse_output = False)
df['type'] = ohe.fit_transform(df[['type']])
df

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0      0.0       7.216573          0.344123     0.318738        5.053839   
1      0.0       7.216573          0.344123     0.318738        5.053839   
2      0.0       7.216573          0.344123     0.318738        5.053839   
3      0.0       7.216573          0.344123     0.318738        5.053839   
6      0.0       7.216573          0.344123     0.318738        5.053839   
...    ...            ...               ...          ...             ...   
6491   1.0       7.216573          0.344123     0.318738        5.053839   
6492   1.0       7.216573          0.344123     0.318738        5.053839   
6493   1.0       7.216573          0.344123     0.318738        5.053839   
6495   1.0       7.216573          0.344123     0.318738        5.053839   
6496   1.0       7.216573          0.344123     0.318738        5.053839   

      chlorides  free sulfur dioxide  total sulfur dioxide  density        pH  \
0      0.056668                 45.0                 170.0  1.00100  3.224434   
1      0.056668                 14.0                 132.0  0.99400  3.224434   
2      0.056668                 30.0                  97.0  0.99510  3.224434   
3      0.056668                 47.0                 186.0  0.99560  3.224434   
6      0.056668                 30.0                 136.0  0.99490  3.224434   
...         ...                  ...                   ...      ...       ...   
6491   0.056668                 28.0                  38.0  0.99651  3.224434   
6492   0.056668                 32.0                  44.0  0.99490  3.224434   
6493   0.056668                 39.0                  51.0  0.99512  3.224434   
6495   0.056668                 32.0                  44.0  0.99547  3.224434   
6496   0.056668                 18.0                  42.0  0.99549  3.224434   

      sulphates  alcohol  quality  
0      0.533268      8.8        6  
1      0.533268      9.5        6  
2      0.533268     10.1        6  
3      0.533268      9.9        6  
6      0.533268      9.6        6  
...         ...      ...      ...  
6491   0.533268      9.5        6  
6492   0.533268     10.5        5  
6493   0.533268     11.2        6  
6495   0.533268     10.2        5  
6496   0.533268     11.0        6  

[5329 rows x 13 columns]

initialize the feature cols and target col

In [75]:
X = df.drop(columns = 'quality')
Y = df['quality']

split the data into train and test data

In [76]:
xtrain, xtest, ytrain, ytest = train_test_split(X, Y, test_size= 0.2, random_state= 2)

Create the model's object to train the model then predict the target

different   model's can be train

Model can train by LinearRegressor

In [77]:
lr = LinearRegression()
lr.fit(xtrain, ytrain)
y_pred_lr = lr.predict(xtest)
y_pred_lr

array([5.35523737, 5.73191344, 5.3584248 , ..., 5.89809843, 6.33371452,
       5.2710027 ])

Model can train by k nearest neighbor regressor

In [78]:
knn = KNeighborsRegressor(n_neighbors= 5)
knn.fit(xtrain, ytrain)
y_pred_knn = knn.predict(xtest)
y_pred_knn

array([6. , 5.4, 5.6, ..., 6. , 7. , 5.8])

Model can train by Decision Tree Regressor

In [79]:
dtr = DecisionTreeRegressor()
dtr.fit(xtrain, ytrain)
y_pred_dtr = dtr.predict(xtest)
y_pred_dtr

array([5., 6., 5., ..., 6., 6., 5.])

Model can train by Random Froest Regressor

In [80]:
rfr = RandomForestRegressor()
rfr.fit(xtrain, ytrain)
y_pred_rfr = rfr.predict(xtest)
y_pred_rfr

array([5.45, 5.78, 5.21, ..., 5.59, 6.07, 4.99])

Check the cross validation score for all the different model's

In [81]:
def cross_val(model):
    cross_val_data = cross_val_score(model , X, Y, cv= 10)
    cross_val_data_mean = cross_val_data.sum()/len(cross_val_data)
    print(f"The cross validation score of the {model} is", cross_val_data_mean)

In [82]:
cross_val(lr)

The cross validation score of the LinearRegression() is 0.22223834922744193


In [83]:
cross_val(knn)

The cross validation score of the KNeighborsRegressor() is 0.027887980080920027


In [84]:
cross_val(dtr)

The cross validation score of the DecisionTreeRegressor() is -0.5583585437995605


In [85]:
cross_val(rfr)

The cross validation score of the RandomForestRegressor() is 0.1883724401314347


Hyper Parameter Tunning 

In [96]:
hyperparameter = {

        'lr' : {
            'n_jobs' : [-1, None]
        },

        'knn' : {
            'n_neighbors' : [5,8, 10],
            'leaf_size' : [10, 15, 20, 25, 30]
        },

        'dtr' : {
            'max_depth' : [1,2,3,4],
            'max_leaf_nodes' : [4,5,6,7,8],
            'min_samples_split' : [2,3,4],
            'random_state' : [2, 3,4, None]
        },

        'rfr' : {
            'n_estimators' : [10,50,80,100],
            'max_depth' : [1,2,3,4],
            'max_leaf_nodes' : [4,5,6,7,8],
            'min_samples_split' : [2,3,4],
            'random_state' : [2, 3,4, None]
        }

}

In [97]:
steps = {
    'lr' : LinearRegression(),
    'knn' : KNeighborsRegressor(),
    'dtr' : DecisionTreeRegressor(),
    'rfr' : RandomForestRegressor()
}

hyper parameter tunning by Grid search cv

In [98]:
for value, key in steps.items():
    gscv = GridSearchCV(estimator= key, param_grid= hyperparameter[value], cv = 5)
    gscv.fit(xtrain, ytrain)
    y_pred_gscv = gscv.predict(xtest)


    print(f"The grid search cv best score of the {key} is", gscv.best_score_)
    print(f"The grid search cv best parameter of the {key} is", gscv.best_params_)

The grid search cv best score of the LinearRegression() is 0.24245894522465986
The grid search cv best parameter of the LinearRegression() is {'n_jobs': -1}
The grid search cv best score of the KNeighborsRegressor() is 0.1222252470068714
The grid search cv best parameter of the KNeighborsRegressor() is {'leaf_size': 10, 'n_neighbors': 10}
The grid search cv best score of the DecisionTreeRegressor() is 0.24062239468079807
The grid search cv best parameter of the DecisionTreeRegressor() is {'max_depth': 3, 'max_leaf_nodes': 8, 'min_samples_split': 2, 'random_state': 2}


hyper parameter tunning by randomized search cv

In [99]:
for value, key in steps.items():
    rscv = RandomizedSearchCV(estimator= key, param_distributions = hyperparameter[value], cv = 5)
    rscv.fit(xtrain, ytrain)
    y_pred_gscv = rscv.predict(xtest)


    print(f"The grid search cv best score of the {key} is", rscv.best_score_)
    print(f"The grid search cv best parameter of the {key} is", rscv.best_params_)

c:\Users\AL-HAMD\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_search.py:320: UserWarning: The total space of parameters 2 is smaller than n_iter=10. Running 2 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(


The grid search cv best score of the LinearRegression() is 0.24245894522465986
The grid search cv best parameter of the LinearRegression() is {'n_jobs': -1}
The grid search cv best score of the KNeighborsRegressor() is 0.1222252470068714
The grid search cv best parameter of the KNeighborsRegressor() is {'n_neighbors': 10, 'leaf_size': 20}
The grid search cv best score of the DecisionTreeRegressor() is 0.23317511183462747
The grid search cv best parameter of the DecisionTreeRegressor() is {'random_state': 4, 'min_samples_split': 2, 'max_leaf_nodes': 8, 'max_depth': 4}
The grid search cv best score of the RandomForestRegressor() is 0.24340419108209616
The grid search cv best parameter of the RandomForestRegressor() is {'random_state': None, 'n_estimators': 80, 'min_samples_split': 2, 'max_leaf_nodes': 6, 'max_depth': 4}
